name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        run: echo "$EXPO_CL_TOKEN" | expo login --non-interactive --username ${{ secrets.EXPO_CLI_USERNAME }} --password ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Build Android
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_CL_TOKEN }}

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-android-apk
          path: artifacts/app.apk
